package main;

import com.bulenkov.darcula.DarculaLaf;
import java.awt.event.KeyEvent;

import javax.swing.plaf.basic.BasicLookAndFeel;

/**
 *
 * @author Wesley
 */
public class Main extends javax.swing.JFrame {

    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tensaoEntrada = new javax.swing.JTextField();
        resistor1 = new javax.swing.JTextField();
        resistor2 = new javax.swing.JTextField();
        tensaoSaida = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        calcular = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cálculo de divisão de tensão");
        setIconImage(getToolkit().createImage(getClass().getResource("/main/img/ico.png")));
        setMinimumSize(new java.awt.Dimension(478, 220));
        setPreferredSize(new java.awt.Dimension(478, 188));
        setResizable(false);
        getContentPane().setLayout(null);

        tensaoEntrada.setNextFocusableComponent(resistor1);
        tensaoEntrada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tensaoEntradaKeyPressed(evt);
            }
        });
        getContentPane().add(tensaoEntrada);
        tensaoEntrada.setBounds(140, 40, 80, 24);

        resistor1.setNextFocusableComponent(resistor2);
        resistor1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                resistor1KeyPressed(evt);
            }
        });
        getContentPane().add(resistor1);
        resistor1.setBounds(140, 70, 80, 24);

        resistor2.setNextFocusableComponent(tensaoSaida);
        resistor2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                resistor2KeyPressed(evt);
            }
        });
        getContentPane().add(resistor2);
        resistor2.setBounds(140, 100, 80, 24);

        tensaoSaida.setNextFocusableComponent(calcular);
        tensaoSaida.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tensaoSaidaKeyPressed(evt);
            }
        });
        getContentPane().add(tensaoSaida);
        tensaoSaida.setBounds(140, 130, 80, 24);

        jLabel1.setText("Tensão de entrada");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 40, 106, 16);

        jLabel2.setText("                  R1");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 70, 70, 16);

        jLabel3.setText("                  R2");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 100, 70, 16);

        jLabel4.setText("Tensão de saída");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 130, 93, 16);

        calcular.setText("Calcular");
        calcular.setNextFocusableComponent(jButton2);
        calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularActionPerformed(evt);
            }
        });
        calcular.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                calcularKeyPressed(evt);
            }
        });
        getContentPane().add(calcular);
        calcular.setBounds(270, 30, 77, 32);

        jButton2.setText("Limpar");
        jButton2.setNextFocusableComponent(tensaoEntrada);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton2KeyPressed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(270, 70, 77, 32);

        jLabel5.setText("Volts");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(230, 40, 29, 16);

        jLabel6.setText("ohms");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(230, 70, 32, 16);

        jLabel7.setText("ohms");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(230, 100, 32, 16);

        jLabel8.setText("Volts");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(230, 130, 29, 16);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/100px-Voltage_divider.svg.png"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(360, 20, 100, 130);

        jLabel10.setText("v1.2.1");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(430, 170, 48, 16);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularActionPerformed
        Calc.calcular();
    }//GEN-LAST:event_calcularActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Calc.limpar();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void calcularKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_calcularKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            Calc.calcular();
        }
    }//GEN-LAST:event_calcularKeyPressed

    private void jButton2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton2KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            Calc.limpar();
        }
    }//GEN-LAST:event_jButton2KeyPressed

    private void tensaoEntradaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tensaoEntradaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            resistor1.requestFocus();
        }
    }//GEN-LAST:event_tensaoEntradaKeyPressed

    private void resistor1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_resistor1KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            resistor2.requestFocus();
        }
    }//GEN-LAST:event_resistor1KeyPressed

    private void resistor2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_resistor2KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            tensaoSaida.requestFocus();
        }
    }//GEN-LAST:event_resistor2KeyPressed

    private void tensaoSaidaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tensaoSaidaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            calcular.requestFocus();
        }
    }//GEN-LAST:event_tensaoSaidaKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                BasicLookAndFeel darcula = new DarculaLaf();

                javax.swing.UIManager.setLookAndFeel(darcula);

            }
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton calcular;
    public static javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public static javax.swing.JTextField resistor1;
    public static javax.swing.JTextField resistor2;
    public static javax.swing.JTextField tensaoEntrada;
    public static javax.swing.JTextField tensaoSaida;
    // End of variables declaration//GEN-END:variables
}
